Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:service}-static-${self:custom.stage}

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub '${Bucket.Arn}/*'
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId
          - Action:
              - s3:PutObject
              - s3:DeleteObject
              - s3:ListBucket
            Effect: Allow
            Resource:
              - !Sub '${Bucket.Arn}/*'
              - !GetAtt Bucket.Arn
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
