/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/payment': RouteRecordInfo<'/payment', '/payment', Record<never, never>, Record<never, never>>,
    '/payment/v110': RouteRecordInfo<'/payment/v110', '/payment/v110', Record<never, never>, Record<never, never>>,
    '/payment/v111': RouteRecordInfo<'/payment/v111', '/payment/v111', Record<never, never>, Record<never, never>>,
    '/payment/v204': RouteRecordInfo<'/payment/v204', '/payment/v204', Record<never, never>, Record<never, never>>,
    '/payment/v205': RouteRecordInfo<'/payment/v205', '/payment/v205', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
  }
}
