name: Build - Release

on:
  workflow_dispatch:
  push:
    branches:
      - release/**
      - hotfix/**
      - 868822rze

jobs:

  buildAndTest:
    name: Build & Test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::654654287847:role/sync-web-sdk-internal-us-east-1-github-role
          role-session-name: pipelines

      - name: Build artifact
        run: |
          mkdir ./target
          mkdir ./target/qa
          mkdir ./target/staging
          mkdir ./target/sandbox
          mkdir ./target/prod
          sudo cp serverless.yml ./target/
          sudo cp serverless-env.yml ./target/ 2>/dev/null || :
          sudo cp package.json ./target/
          sudo cp -r resources/ ./target/
          pnpm build
          cp -r dist/ ./target/qa
          cp -r dist/ ./target/staging
          cp -r dist/ ./target/sandbox
          cp -r dist/ ./target/prod
          rm -rf dist/
      - name: Package and Upload Artifact
        run: |
          cd ./target && zip -r latest-release.zip .
          aws s3 cp latest-release.zip s3://sync-web-sdk-internal-us-east-1-build-artifacts/latest-release.zip
